# Generated by Django 4.1.7 on 2023-03-22 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Costing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pet_Qty', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Pet_Rate', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Pet_Cost', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Pet_HST_Qty', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Pet_HST_Rate', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Pet_HST_Cost', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Ink_Cost', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Ink_Cost_PKG', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Met_Qty', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Met_Rate', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Met_Cost', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Met_CPP_Qty', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Met_CPP_Rate', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Met_CPP_Cost', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Foil_9_Mic_Qty', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Foil_9_Mic_Rate', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Foil_9_Mic_Cost', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Foil_30_Mic_Qty', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Foil_30_Mic_Rate', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Foil_30_Mic_Cost', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Polly_Qty', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Polly_Rate', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Polly_Cost', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Lamination_Cost', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Lamination_Cost_PKG', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Lamination_OutPut', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Coating_Cost', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Coating_Cost_PKG', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Zipper_Qty', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Zipper_Rate', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Zipper_Cost', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Total_Cost', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Lami_total_Output', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Sliting_Output', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Print_Westag', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Lamination_Westag', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Trim_Westag', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Pouch_Westag', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Net_Raw_Material', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Finished_Good', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Wet_Gain_Loss', models.DecimalField(decimal_places=3, max_digits=20)),
                ('Total_Cost_PKG', models.DecimalField(decimal_places=3, max_digits=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
