# Generated by Django 4.1.7 on 2023-03-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costing',
            name='Job_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='costing',
            name='Job_Size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
