# Generated by Django 4.1.7 on 2023-03-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0002_costing_job_name_costing_job_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costing',
            name='user',
        ),
    ]
