# Generated by Django 4.1.7 on 2023-03-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0004_alter_costing_coating_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costing',
            name='Lamination_Cost_PKG_Polly',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='costing',
            name='Lamination_Cost_Polly',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='costing',
            name='Lamination_OutPut_Polly',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
    ]
