# Generated by Django 4.1.7 on 2023-03-27 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0007_costing_lamination_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='costing',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
