# Generated by Django 4.1.7 on 2023-03-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0003_remove_costing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costing',
            name='Coating_Cost',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Coating_Cost_PKG',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Finished_Good',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Foil_30_Mic_Cost',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Foil_30_Mic_Qty',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Foil_30_Mic_Rate',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Foil_9_Mic_Cost',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Foil_9_Mic_Qty',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Foil_9_Mic_Rate',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Ink_Cost',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Ink_Cost_PKG',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Lami_total_Output',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Lamination_Cost',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Lamination_Cost_PKG',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Lamination_OutPut',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Lamination_Westag',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Met_CPP_Cost',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Met_CPP_Qty',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Met_CPP_Rate',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Met_Cost',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Met_Qty',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Met_Rate',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Net_Raw_Material',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Pet_Cost',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Pet_HST_Cost',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Pet_HST_Qty',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Pet_HST_Rate',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Pet_Qty',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Pet_Rate',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Polly_Cost',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Polly_Qty',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Polly_Rate',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Pouch_Westag',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Print_Westag',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Sliting_Output',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Total_Cost',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Total_Cost_PKG',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Trim_Westag',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Wet_Gain_Loss',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Zipper_Cost',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Zipper_Qty',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='costing',
            name='Zipper_Rate',
            field=models.DecimalField(decimal_places=3, max_digits=20, null=True),
        ),
    ]
