# Generated by Django 4.1.7 on 2023-03-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0010_printing_alter_costing_coating_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lamination_Sheet', models.CharField(max_length=255, null=True)),
                ('Rate', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
