# Generated by Django 4.1.7 on 2023-03-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0011_lamination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamination',
            name='Rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='printing',
            name='Rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
