# Generated by Django 4.1.7 on 2023-03-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0013_costing_printing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='costing',
            name='lamination_dropdown',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
