# Generated by Django 4.1.7 on 2023-03-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0014_costing_lamination_dropdown'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costing',
            old_name='lamination_dropdown',
            new_name='lamination_Type',
        ),
    ]
