# Generated by Django 4.1.7 on 2023-03-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0015_rename_lamination_dropdown_costing_lamination_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costing',
            old_name='lamination_Type',
            new_name='Lamination_Type',
        ),
    ]
