# Generated by Django 4.1.7 on 2023-03-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0016_rename_lamination_type_costing_lamination_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='costing',
            name='Printing_Qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
