# Generated by Django 4.1.7 on 2023-03-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0017_costing_printing_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costing',
            name='Printing_Qty',
        ),
    ]
