# Generated by Django 4.1.7 on 2023-04-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0019_alter_costing_coating_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costing',
            name='Poly_Cost',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='costing',
            name='Poly_Qty',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='costing',
            name='Poly_Rate',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=20, null=True),
        ),
    ]
